import json,time,sys,hashlib,subprocess
from pathlib import Path
from playwright.sync_api import sync_playwright
from browser_smoke import serve_assets,APP_ORIGIN
import browser_env
car=sys.argv[1] if len(sys.argv)>1 else 'eagle'
out=Path('reports/audit2/preparation')/car;out.mkdir(parents=True,exist_ok=True)
(out/'build-inputs.json').write_text(json.dumps({'commit':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'buildFiles':{str(p):hashlib.sha256(p.read_bytes()).hexdigest()for p in [Path('build/web/app.js'),Path('build/web/sim.js'),Path('build/web/race3d.js')]}},indent=2))
with sync_playwright() as pw:
 b=pw.chromium.launch(**browser_env.launch_kwargs(pw,['--no-sandbox','--enable-unsafe-swiftshader']));c=b.new_context(viewport={'width':412,'height':892},record_video_dir=str(out/'video'));serve_assets(c,Path('build/web').resolve());p=c.new_page();errors=[];p.on('pageerror',lambda e:errors.append(str(e)));p.goto(APP_ORIGIN+'/assets/index.html?profile=vehicle-qa');p.wait_for_function('!!window.__EA888_DEBUG__');p.evaluate('(id)=>__EA888_DEBUG__.qaDrive(id)',car);p.locator('[data-nav=dyno]').click();p.locator('[data-action=start-dyno]').click();p.wait_for_selector('[data-action=abort-dyno]',state='detached',timeout=90000);assert p.evaluate('__EA888_DEBUG__.qaStartPreparation()');p.evaluate('''()=>{const el=document.createElement('pre');el.style='position:fixed;top:305px;left:10px;z-index:99999;background:#000a;color:#bdf;font:10px monospace;pointer-events:none';document.body.append(el);setInterval(()=>{const d=__EA888_DEBUG__.preparation(),r=__EA888_DEBUG__.race(),p=d?.physical;if(p)el.textContent=`QA ${r.phase} · world ${d.point?.worldM?.toFixed(2)} m\n${p.speedKmh.toFixed(1)} km/u · ${p.rpm.toFixed(0)} rpm · gear ${p.gear}\nwheel ${p.wheelRpm.toFixed(0)} rpm · slip ${p.slipRatio.toFixed(2)} · wet ${p.wetness.toFixed(2)}\nrolling ${d.state.rollingS.toFixed(2)} s · core ${p.tyreBulkC.toFixed(0)}°C`;},100);}''');p.wait_for_function('__EA888_DEBUG__.preparation()?.assetsReady',timeout=60000);p.evaluate('document.querySelector("#race3d-canvas").qaIdentity=123');p.screenshot(path=str(out/'approach.png'))
 p.dispatch_event('[data-v7-control=burnout]','pointerdown',{'pointerId':91,'pointerType':'touch','button':0})
 for label,expr in [('waterbox','p.point?.phase==="waterbox"'),('rolling','p.point?.phase==="rolling-burnout"'),('stage','p.point?.worldM>-.8')]:
  
  try:p.wait_for_function('(p=>'+expr+')(__EA888_DEBUG__.preparation())',timeout=120000)
  except Exception:
   (out/'failure.json').write_text(json.dumps(p.evaluate('__EA888_DEBUG__.preparation()'),indent=2));p.screenshot(path=str(out/'failure.png'));raise
  p.screenshot(path=str(out/(label+'.png')));assert p.evaluate('document.querySelector("#race3d-canvas").qaIdentity===123')
 p.dispatch_event('[data-v7-control=creep]','pointerdown',{'pointerId':92,'pointerType':'touch','button':0});p.wait_for_function('__EA888_DEBUG__.stageState().staged',timeout=60000);p.dispatch_event('[data-v7-control=creep]','pointerup',{'pointerId':92,'pointerType':'touch'});p.screenshot(path=str(out/'staged.png'))
 report=p.evaluate('__EA888_DEBUG__.preparation()');report['errors']=errors;(out/'report.json').write_text(json.dumps(report,indent=2));assert not errors
 p.dispatch_event('[data-v7-control=throttle]','pointerdown',{'pointerId':93,'pointerType':'touch','button':0});p.wait_for_function('__EA888_DEBUG__.stageState().green',timeout=20000);p.dispatch_event('[data-v7-control=throttle]','pointerup',{'pointerId':93,'pointerType':'touch'});p.wait_for_timeout(100);p.evaluate('__EA888_DEBUG__.setDriverAssistForTest(true)');p.wait_for_function('__EA888_DEBUG__.race().distanceM>30',timeout=120000);p.screenshot(path=str(out/'race.png'));assert p.evaluate('document.querySelector("#race3d-canvas").qaIdentity===123');p.wait_for_function('__EA888_DEBUG__.race().finished',timeout=180000);report['result']=p.evaluate('__EA888_DEBUG__.lastDrag()');report['sameCanvas']=True;report['model']=p.evaluate('__EA888_DEBUG__.vehicle()');assert report['result']['valid'] and report['result']['quarter']>0,report['result'].get('finishReason');report['ok']=True;(out/'report.json').write_text(json.dumps(report,indent=2));p.screenshot(path=str(out/'finish.png'));p.locator('[data-action=finish-replay]').click();p.wait_for_function('__EA888_DEBUG__.replay().progress>0',timeout=30000);p.screenshot(path=str(out/'replay.png'));c.close();b.close();print('PASS actual preparation/race')
