import json
from pathlib import Path
from playwright.sync_api import sync_playwright
from browser_smoke import serve_assets,APP_ORIGIN
import browser_env
out=Path('reports/audit2/tuner');out.mkdir(parents=True,exist_ok=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(**browser_env.launch_kwargs(pw,['--no-sandbox','--enable-unsafe-swiftshader']));c=b.new_context(viewport={'width':390,'height':844});serve_assets(c,Path('build/web').resolve());p=c.new_page();errors=[];p.on('pageerror',lambda e:errors.append(str(e)));p.on('dialog',lambda d:d.accept('Kwartmijl test') if d.type=='prompt' else d.accept());p.goto(APP_ORIGIN+'/assets/index.html?profile=vehicle-qa');p.wait_for_function('!!window.__EA888_DEBUG__');p.evaluate('__EA888_DEBUG__.qaDrive("eagle")');p.locator('[data-nav=dyno]').click();p.locator('[data-action=start-dyno]').click();p.wait_for_selector('[data-action=abort-dyno]',state='detached',timeout=90000);p.locator('[data-nav=tune]').click();p.locator('[data-tune-panel=gearing]').click();before=p.evaluate('__EA888_DEBUG__.saveSnapshot()');p.locator('#driveline-goal').select_option('lowgrip');p.locator('[data-driveline-search]').click();p.wait_for_selector('[data-driveline-apply]',timeout=180000);p.locator('.driveline-tuner').screenshot(path=str(out/'comparison.png'));assert p.evaluate('__EA888_DEBUG__.saveSnapshot().bank')==before['bank'];p.locator('[data-driveline-apply]').first.click();after=p.evaluate('__EA888_DEBUG__.saveSnapshot()');assert after['bank']<=before['bank'];assert p.evaluate('__EA888_DEBUG__.dyno().current');p.locator('[data-driveline-save]').click();p.evaluate('__EA888_DEBUG__.flushSave()');p.reload();p.wait_for_function('!!window.__EA888_DEBUG__');p.locator('[data-nav=tune]').click();p.locator('[data-tune-panel=gearing]').click();p.wait_for_selector('[data-driveline-load]');p.screenshot(path=str(out/'saved-setup.png'));p.locator('[data-driveline-undo]').click();assert p.evaluate('__EA888_DEBUG__.saveSnapshot().bank')==before['bank'];assert p.locator('[data-driveline-load]').count()>0;assert not errors; (out/'report.json').write_text(json.dumps({'ok':True,'beforeBank':before['bank'],'afterBank':after['bank'],'errors':errors},indent=2));p.locator('[data-driveline-search]').click();p.wait_for_selector('[data-driveline-apply]',timeout=180000);p.locator('[data-driveline-apply]').first.click();runs=[]
 for i in range(2):
  if not p.evaluate('__EA888_DEBUG__.dyno().current'):
   p.locator('[data-nav=dyno]').click();p.locator('[data-action=start-dyno]').click();p.wait_for_selector('[data-action=abort-dyno]',state='detached',timeout=90000)
  assert p.evaluate('__EA888_DEBUG__.qaStartRun()');p.wait_for_function('__EA888_DEBUG__.race().finished',timeout=180000);r=p.evaluate('__EA888_DEBUG__.lastDrag()');assert r['valid'] and r['quarter']>0;runs.append({'quarter':r['quarter'],'valid':r['valid']});p.screenshot(path=str(out/f'after-tune-race-{i}.png'));p.evaluate('__EA888_DEBUG__.qaCloseRace()')
 (out/'race-route.json').write_text(json.dumps({'runs':runs,'errors':errors}));assert not errors;b.close();print('PASS real worker comparison, buy, named save, restart, undo')
