#!/usr/bin/env node
'use strict';
// Builds src/assets/roster-data.js from data/roster/*.json (made by tools/import_roster.py).
//   node tools/build_roster_data.js          write the runtime bundle
//   node tools/build_roster_data.js --check  exit 1 when the bundle is out of date
// The WebView loads it as a plain script (no fetch of file://), like engine-data.js.
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'data', 'roster');
const OUT = path.join(ROOT, 'src', 'assets', 'roster-data.js');
const read = name => JSON.parse(fs.readFileSync(path.join(SRC, name), 'utf8'));
const optional = (name, fallback) => (fs.existsSync(path.join(SRC, name)) ? read(name) : fallback);

function build() {
  const cars = read('cars.json');
  const names = read('display-names.json');
  const data = {
    schemaVersion: 1,
    generatedBy: 'tools/build_roster_data.js',
    source: cars.source,
    kinds: cars.kinds,
    // display names come from display-names.json so they can be edited without a re-import
    cars: cars.cars.map(c => ({ ...c, displayName: names[c.id] || c.id })),
    calibration: read('calibration.json'),
    rules: read('model-rules.json'),
    parts: optional('parts-catalog.json', null),
    workshop: optional('workshop.json', { cars: {}, parts: {}, shared: {} }),
    currency: optional('currency.json', { usdToEur: null, reason: 'geen koers ingesteld' })
  };
  return `/* GENERATED by tools/build_roster_data.js from data/roster/*.json - do not edit by hand.
 * Real cars, runs and part prices from the YouTube research (${cars.source.repo} ${cars.source.branch} @ ${cars.source.commit}).
 * Every value carries its source (video id + timestamp) and kind: measured / stated / estimate from the research,
 * modeled = filled in by the game with the reason. Names shown in the game: data/roster/display-names.json.
 */
(function (root) {
  'use strict';
  const DATA = ${JSON.stringify(data)};
  if (typeof module !== 'undefined' && module.exports) module.exports = DATA;
  root.EA888_ROSTER_DATA = DATA;
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;
}

const text = build();
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== text) { console.error('src/assets/roster-data.js is out of date: run node tools/build_roster_data.js'); process.exit(1); }
  console.log('roster-data.js up to date');
} else {
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${text.length} bytes)`);
}
