#!/usr/bin/env node
'use strict';
// Builds src/assets/engine-data.js from the source datasets in data/engine/.
//   node tools/build_engine_data.js          write the runtime bundle
//   node tools/build_engine_data.js --check  exit 1 when the bundle is out of date
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'data', 'engine');
const OUT = path.join(ROOT, 'src', 'assets', 'engine-data.js');
const read = name => JSON.parse(fs.readFileSync(path.join(SRC, name), 'utf8'));
const optional = name => (fs.existsSync(path.join(SRC, name)) ? read(name) : {});

function build() {
  const fuels = read('fuels.json');
  const heads = read('heads.json');
  const cal = read('calibration.json');
  const fuelSystems = optional('fuel-systems.json');
  const data = {
    schemaVersion: 1,
    generatedBy: 'tools/build_engine_data.js',
    calibration: cal.constants,
    references: cal.references,
    fuelComponents: fuels.components,
    fuelGrades: fuels.grades,
    water: fuels.water,
    heads: heads.heads,
    fuelSystems: fuelSystems.systems || {},
    injectors: fuelSystems.injectors || {},
    pumps: fuelSystems.pumps || {},
    blocks: optional('blocks.json').blocks || {},
    oils: optional('oils.json').oils || {}
  };
  return `/* GENERATED by tools/build_engine_data.js from data/engine/*.json - do not edit by hand.
 * Engine breathing, combustion, fuel and fuel-system data with provenance. mapType "measured"/"vendor" =
 * published data; "modeled" = engineering approximation calibrated to the references in calibration.json.
 */
(function (root) {
  'use strict';
  const DATA = ${JSON.stringify(data)};
  if (typeof module !== 'undefined' && module.exports) module.exports = DATA;
  root.EA888_ENGINE_DATA = DATA;
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;
}

const text = build();
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== text) { console.error('src/assets/engine-data.js is out of date: run node tools/build_engine_data.js'); process.exit(1); }
  console.log('engine-data.js up to date');
} else {
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${text.length} bytes)`);
}
